language: node_js

node_js:
- '0.11'
- '0.10'

before_install:
- gem update --system
- gem install sass
- npm install -g grunt-cli

install: npm install

before_script: grunt build

env:
  global:
  - FTP_USER=SANDUSER
  - FTP_PASSWORD=SANDPASS
  - secure: A8GYFi/1BtXA3Ey4JaeqT4TjSR+jv73855I/LV68LXUgp6PqUu6WJvUo1v/m/QSC1utety5k0tlZjH/pe8iVSV/Eu8meOOo+zytdTsSAGOQ94RStfOaJJTKfsr4naZfQAhl448ptB2xnG6Ko8mkoz12qRVy2mmuaigOysJlQ0HM=
  - secure: fKPPZcuIinsbNEbvUGRUIf7ePIDwDDxDEW4cNBi7Eg1KXJrkYhbxR6DUp44215DhzBZGqDNJZxCBufjpf/3u1CyNCwHQqfcl1gqfYvLSWck8VjKobCsizbIw3bWCMTd5gB2V0FKpmH9O+P4IF7kK7qm8G8lKQJr5QMGLIoDhrV4=

after_success: curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp:bokamontenegro.com/travisdir
