language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
before_install:
- gem update --system
- gem install sass
- npm install -g grunt-cli
install: npm install
before_script: grunt build
env:
  global:
  - FTP_USER=SANDUSER
  - FTP_PASSWORD=SANDPASS
  - secure: PF3J/IZwmhY8RRM2FJkAiz6lHDZIR7xQ6lXLIwLSyombvVOLb8P/kO8m2hheCBnbfha5tiWfKO06HovnGjk+z673/vXTv3LiXaMuVHtX0uAN5rccr8dkQVlYgp2SFl0ap9sod/1+w0qmLdavfD7XHe3dm+nfPE9gSNWjo7tNLE0=
  - secure: jyhVsLs54wfH1zeIy9ZPR6yqA1kUjHLxjKavC2tCxImMfGLna+9CSf+DYmi0VRQ9ZEFAj/NqatiTtcZTYyLO7fmHhtKaMFCl+3JbOZrjMvXacx246H5YgsQvcicCnYAd32CQAugKEAlzkizCqeujsuAtpTOq2DjhR8SPkRvyIWw=
after_success: curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp:bokamontenegro.com/travisdir
